name: xeus-nelson
channels:
  - conda-forge
dependencies:
  # Build dependencies
  - cmake
  - ninja
  - cxx-compiler
  # Host dependencies
  - xeus>=5.0.0
  - xeus-zmq>=3.0,<4.0
  - nlohmann_json=3.11.3
  - nelson-core >=0.3,<0.4
  # Test dependencies
  - pytest
  - jupyter_kernel_test>=0.5,<0.6
  - nbval
  - pytest-rerunfailures
